class Club < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '陸上競技部' },
    { id: 2, name: 'サッカー部' },
    { id: 3, name: '野球部' },
    { id: 4, name: 'ハンドボール部' },
    { id: 5, name: 'テニス部' },
    { id: 6, name: 'ソフトテニス部' },
    { id: 7, name: 'バレーボール部' },
    { id: 8, name: 'バスケットボール部' },
    { id: 9, name: 'バドミントン部' },
    { id: 10, name: '卓球部' },
    { id: 11, name: '体操部' },
    { id: 12, name: '柔道部' },
    { id: 13, name: '剣道部' },
    { id: 14, name: '弓道部' },
    { id: 15, name: '水泳部' },
    { id: 16, name: '放送部' },
    { id: 17, name: '科学部' },
    { id: 18, name: '美術部' },
    { id: 19, name: '書道部' },
    { id: 20, name: '囲碁・棋道部' },
    { id: 21, name: '吹奏楽部' },
    { id: 22, name: '調理部' },
    { id: 23, name: '茶道部' },
    { id: 24, name: '合唱部' },
    { id: 25, name: '文芸部' },
    { id: 26, name: '演劇部' },
    { id: 27, name: '新聞部' },
    { id: 28, name: 'ダンス部' },
    { id: 29, name: '軽音楽部' },
    { id: 30, name: '写真部' }
  ]
end
